name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: your-docker-username/your-microservice:latest

      - name: Deploy to Staging
        uses: easingthemes/ssh-deploy@v2
        with:
          host: ${{ secrets.STAGING_SERVER_HOST }}
          username: ${{ secrets.STAGING_SERVER_USERNAME }}
          key: ${{ secrets.STAGING_SERVER_KEY }}
          port: ${{ secrets.STAGING_SERVER_PORT }}
          source: .

      - name: Deploy to Production
        uses: easingthemes/ssh-deploy@v2
        with:
          host: ${{ secrets.PRODUCTION_SERVER_HOST }}
          username: ${{ secrets.PRODUCTION_SERVER_USERNAME }}
          key: ${{ secrets.PRODUCTION_SERVER_KEY }}
          port: ${{ secrets.PRODUCTION_SERVER_PORT }}
          source: .
